[package]
name = "plot-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui = "0.27"
egui_plot = "0.27"
eframe = "0.27"
c3dio = "0.8.0"
butterworth = "0.1.0"
